--ozone-platform-hint=wayland
#--enable-blink-features=MiddleClickAutoscroll
--enable-features=AcceleratedVideoEncoder,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecodeLinuxGL,VaapiOnNvidiaGPUs,WaylandLinuxDrmSyncobj,UseOzonePlatform
