# https://wiki.hyprland.org/Configuring/Keywords/#executing

# apps
exec-once = $uwsm nm-applet & $uwsm blueman-applet
exec-once = systemctl --user start swww-daemon.service
exec-once = systemctl --user start waybar.service
exec-once = systemctl --user start swayosd-server.service
exec-once = systemctl --user start cliphist.service 
exec-once = $uwsm kdeconnect-indicator
exec-once = systemctl --user start hyprpolkitagent.service
exec-once = systemctl --user start hypridle.service
exec-once = systemctl --user start swaync.service
exec-once = systemctl --user start qpwgraph.service
exec-once = $uwsm hyprls
exec-once = systemctl --user start hyprsunset.service
# I use sleep, because swaync is not instantly get launched.
# I mean, I could use systemd native autostart, but I want to keep here everything, in hypr cfgs.
exec-once = sleep 2 && $uwsm $browser
exec-once = $HOME/debug.sh
# workaround to use my monitor as primary
exec-once = hyprctl dispatch workspace 1 
# hyprpm
#exec-once = hyprpm reload -n
