# https://wiki.hyprland.org/Configuring/Permissions/
#ecosystem:enforce_permissions = true
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

permission = /usr/bin/grim, screencopy, allow

permission = /usr/bin/swaylock, screencopy, allow
permission = /usr/bin/hyprlock, screencopy, allow
permission = /usr/bin/hyprpicker, screencopy, allow
permission = /usr/bin/wayvnc, screencopy, allow
