# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# PiP from browsers 

windowrule = float, title:^(Picture in picture)$
windowrule = pin, title:^(Picture in picture)$ 
windowrule = float, title:^(Картинка в картинці)$
windowrule = pin, title:^(Картинка в картинці)$ 
# W for hyprland contributors, especially those who implemented keep aspect ratio!!
windowrule = keepaspectratio, title:^(Picture in picture)$
windowrule = keepaspectratio, title:^(Картинка в картинці)$ 
#windowrule = size 426 240, class:floorp-default, title:Picture-in-Picture
windowrule = pin, class: floorp-default, title:Picture-in-Picture
windowrule = float, class:floorp-default, title:Picture-in-Picture
windowrule = opacity 1 override 1 override, class:floorp-default, title:floorp-default
windowrule = opacity 1 override 1 override, title:^(Картинка в картинці)$


# For some reason, "Play in TV" feature in chromium don't have it's own title
# So that's why I wrote this blank.
# Also, without it being floaty - it will close no matter what. 
#windowrule = float, class: , title: 
#NVM, IT TRIGERS EVERYTHING, GOD DAMN IT

# Transparency tweaks
windowrule = opacity 0.8 override 0.8 overried, class:kitty
windowrule = opacity 0.8 0.8, class:spotify


# GAMING
windowrule = noanim, class:org.vinegarhq.Sober

# Ignore maximize requests from apps. 
windowrule = suppressevent maximize, class:.*
windowrule = idleinhibit fullscreen, class:.* 

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Misc
windowrule = float, class:thunar, title:Прогрес файлової операції
windowrule = float, class:org.pulseaudio.pavucontrol, title:Керування гучністю
windowrule = float, class:Nemo-preview-start
windowrule = center 1, class:Nemo-preview-start
windowrule = float, class:engrampa
windowrule = float, class:org.gnome.Calculator
windowrule = float, class: onboard
windowrule = float, class:org.kde.kdeconnect.daemon
windowrule = float, class:org.gnome.Calendar
windowrule = float, title: Перейменувати .*
windowrule = float, class: nm.*
windowrule = float, class: blueman-manager
windowrule = float, class: hyprland-share-picker
windowrule = float, class:vesktop, title:Discord Popout
windowrule = pin, class:vesktop, title:Discord Popout
windowrule = float, class:xdg-desktop-portal-gtk
